name: Github Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Specify the Ruby version compatible with Jekyll
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --destination dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jekyll-build
          path: dist